/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedAdminRouteImport } from './routes/_authed-admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminAccessRouteImport } from './routes/admin-access'
import { Route as CareerServicesRouteImport } from './routes/career-services'
import { Route as CertificationsRouteImport } from './routes/certifications'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AuthedAdminAdminIndexRouteImport } from './routes/_authed-admin/admin/index'
import { Route as AuthedAdminAdminAnalyticsRouteImport } from './routes/_authed-admin/admin/analytics'
import { Route as AuthedAdminAdminCertificatesRouteImport } from './routes/_authed-admin/admin/certificates'
import { Route as AuthedAdminAdminCoursesRouteImport } from './routes/_authed-admin/admin/courses'
import { Route as AuthedAdminAdminEbooksRouteImport } from './routes/_authed-admin/admin/ebooks'
import { Route as AuthedAdminAdminEnrollmentsRouteImport } from './routes/_authed-admin/admin/enrollments'
import { Route as AuthedAdminAdminPaymentsRouteImport } from './routes/_authed-admin/admin/payments'
import { Route as AuthedAdminAdminResumeTemplatesRouteImport } from './routes/_authed-admin/admin/resume-templates'
import { Route as AuthedAdminAdminSettingsRouteImport } from './routes/_authed-admin/admin/settings'
import { Route as AuthedAdminAdminUsersRouteImport } from './routes/_authed-admin/admin/users'
import { Route as AuthedDashboardIndexRouteImport } from './routes/_authed/dashboard/index'
import { Route as AuthedDashboardCareerToolkitRouteImport } from './routes/_authed/dashboard/career-toolkit'
import { Route as AuthedDashboardCertificatesRouteImport } from './routes/_authed/dashboard/certificates'
import { Route as AuthedDashboardCoursesRouteImport } from './routes/_authed/dashboard/courses'
import { Route as AuthedDashboardEbookRouteImport } from './routes/_authed/dashboard/ebook'
import { Route as AuthedDashboardProfileRouteImport } from './routes/_authed/dashboard/profile'
import { Route as AuthedDashboardProgressRouteImport } from './routes/_authed/dashboard/progress'
import { Route as AuthedDashboardSettingsRouteImport } from './routes/_authed/dashboard/settings'
import { Route as AuthedAdminAdminStudentsStudentIdRouteImport } from './routes/_authed-admin/admin/students.$studentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAdminRoute = AuthedAdminRouteImport.update({
  id: '/_authed-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAccessRoute = AdminAccessRouteImport.update({
  id: '/admin-access',
  path: '/admin-access',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerServicesRoute = CareerServicesRouteImport.update({
  id: '/career-services',
  path: '/career-services',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationsRoute = CertificationsRouteImport.update({
  id: '/certifications',
  path: '/certifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAdminAdminIndexRoute = AuthedAdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminAdminAnalyticsRoute =
  AuthedAdminAdminAnalyticsRouteImport.update({
    id: '/admin/analytics',
    path: '/admin/analytics',
    getParentRoute: () => AuthedAdminRoute,
  } as any)
const AuthedAdminAdminCertificatesRoute =
  AuthedAdminAdminCertificatesRouteImport.update({
    id: '/admin/certificates',
    path: '/admin/certificates',
    getParentRoute: () => AuthedAdminRoute,
  } as any)
const AuthedAdminAdminCoursesRoute = AuthedAdminAdminCoursesRouteImport.update({
  id: '/admin/courses',
  path: '/admin/courses',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminAdminEbooksRoute = AuthedAdminAdminEbooksRouteImport.update({
  id: '/admin/ebooks',
  path: '/admin/ebooks',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminAdminEnrollmentsRoute =
  AuthedAdminAdminEnrollmentsRouteImport.update({
    id: '/admin/enrollments',
    path: '/admin/enrollments',
    getParentRoute: () => AuthedAdminRoute,
  } as any)
const AuthedAdminAdminPaymentsRoute =
  AuthedAdminAdminPaymentsRouteImport.update({
    id: '/admin/payments',
    path: '/admin/payments',
    getParentRoute: () => AuthedAdminRoute,
  } as any)
const AuthedAdminAdminResumeTemplatesRoute =
  AuthedAdminAdminResumeTemplatesRouteImport.update({
    id: '/admin/resume-templates',
    path: '/admin/resume-templates',
    getParentRoute: () => AuthedAdminRoute,
  } as any)
const AuthedAdminAdminSettingsRoute =
  AuthedAdminAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthedAdminRoute,
  } as any)
const AuthedAdminAdminUsersRoute = AuthedAdminAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedDashboardIndexRoute = AuthedDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardCareerToolkitRoute =
  AuthedDashboardCareerToolkitRouteImport.update({
    id: '/dashboard/career-toolkit',
    path: '/dashboard/career-toolkit',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedDashboardCertificatesRoute =
  AuthedDashboardCertificatesRouteImport.update({
    id: '/dashboard/certificates',
    path: '/dashboard/certificates',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedDashboardCoursesRoute = AuthedDashboardCoursesRouteImport.update({
  id: '/dashboard/courses',
  path: '/dashboard/courses',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardEbookRoute = AuthedDashboardEbookRouteImport.update({
  id: '/dashboard/ebook',
  path: '/dashboard/ebook',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardProfileRoute = AuthedDashboardProfileRouteImport.update({
  id: '/dashboard/profile',
  path: '/dashboard/profile',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardProgressRoute = AuthedDashboardProgressRouteImport.update({
  id: '/dashboard/progress',
  path: '/dashboard/progress',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardSettingsRoute = AuthedDashboardSettingsRouteImport.update({
  id: '/dashboard/settings',
  path: '/dashboard/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminAdminStudentsStudentIdRoute =
  AuthedAdminAdminStudentsStudentIdRouteImport.update({
    id: '/admin/students/$studentId',
    path: '/admin/students/$studentId',
    getParentRoute: () => AuthedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin-access': typeof AdminAccessRoute
  '/career-services': typeof CareerServicesRoute
  '/certifications': typeof CertificationsRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/analytics': typeof AuthedAdminAdminAnalyticsRoute
  '/admin/certificates': typeof AuthedAdminAdminCertificatesRoute
  '/admin/courses': typeof AuthedAdminAdminCoursesRoute
  '/admin/ebooks': typeof AuthedAdminAdminEbooksRoute
  '/admin/enrollments': typeof AuthedAdminAdminEnrollmentsRoute
  '/admin/payments': typeof AuthedAdminAdminPaymentsRoute
  '/admin/resume-templates': typeof AuthedAdminAdminResumeTemplatesRoute
  '/admin/settings': typeof AuthedAdminAdminSettingsRoute
  '/admin/users': typeof AuthedAdminAdminUsersRoute
  '/dashboard/career-toolkit': typeof AuthedDashboardCareerToolkitRoute
  '/dashboard/certificates': typeof AuthedDashboardCertificatesRoute
  '/dashboard/courses': typeof AuthedDashboardCoursesRoute
  '/dashboard/ebook': typeof AuthedDashboardEbookRoute
  '/dashboard/profile': typeof AuthedDashboardProfileRoute
  '/dashboard/progress': typeof AuthedDashboardProgressRoute
  '/dashboard/settings': typeof AuthedDashboardSettingsRoute
  '/admin/': typeof AuthedAdminAdminIndexRoute
  '/dashboard/': typeof AuthedDashboardIndexRoute
  '/admin/students/$studentId': typeof AuthedAdminAdminStudentsStudentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin-access': typeof AdminAccessRoute
  '/career-services': typeof CareerServicesRoute
  '/certifications': typeof CertificationsRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/analytics': typeof AuthedAdminAdminAnalyticsRoute
  '/admin/certificates': typeof AuthedAdminAdminCertificatesRoute
  '/admin/courses': typeof AuthedAdminAdminCoursesRoute
  '/admin/ebooks': typeof AuthedAdminAdminEbooksRoute
  '/admin/enrollments': typeof AuthedAdminAdminEnrollmentsRoute
  '/admin/payments': typeof AuthedAdminAdminPaymentsRoute
  '/admin/resume-templates': typeof AuthedAdminAdminResumeTemplatesRoute
  '/admin/settings': typeof AuthedAdminAdminSettingsRoute
  '/admin/users': typeof AuthedAdminAdminUsersRoute
  '/dashboard/career-toolkit': typeof AuthedDashboardCareerToolkitRoute
  '/dashboard/certificates': typeof AuthedDashboardCertificatesRoute
  '/dashboard/courses': typeof AuthedDashboardCoursesRoute
  '/dashboard/ebook': typeof AuthedDashboardEbookRoute
  '/dashboard/profile': typeof AuthedDashboardProfileRoute
  '/dashboard/progress': typeof AuthedDashboardProgressRoute
  '/dashboard/settings': typeof AuthedDashboardSettingsRoute
  '/admin': typeof AuthedAdminAdminIndexRoute
  '/dashboard': typeof AuthedDashboardIndexRoute
  '/admin/students/$studentId': typeof AuthedAdminAdminStudentsStudentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed-admin': typeof AuthedAdminRouteWithChildren
  '/about': typeof AboutRoute
  '/admin-access': typeof AdminAccessRoute
  '/career-services': typeof CareerServicesRoute
  '/certifications': typeof CertificationsRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authed-admin/admin/analytics': typeof AuthedAdminAdminAnalyticsRoute
  '/_authed-admin/admin/certificates': typeof AuthedAdminAdminCertificatesRoute
  '/_authed-admin/admin/courses': typeof AuthedAdminAdminCoursesRoute
  '/_authed-admin/admin/ebooks': typeof AuthedAdminAdminEbooksRoute
  '/_authed-admin/admin/enrollments': typeof AuthedAdminAdminEnrollmentsRoute
  '/_authed-admin/admin/payments': typeof AuthedAdminAdminPaymentsRoute
  '/_authed-admin/admin/resume-templates': typeof AuthedAdminAdminResumeTemplatesRoute
  '/_authed-admin/admin/settings': typeof AuthedAdminAdminSettingsRoute
  '/_authed-admin/admin/users': typeof AuthedAdminAdminUsersRoute
  '/_authed/dashboard/career-toolkit': typeof AuthedDashboardCareerToolkitRoute
  '/_authed/dashboard/certificates': typeof AuthedDashboardCertificatesRoute
  '/_authed/dashboard/courses': typeof AuthedDashboardCoursesRoute
  '/_authed/dashboard/ebook': typeof AuthedDashboardEbookRoute
  '/_authed/dashboard/profile': typeof AuthedDashboardProfileRoute
  '/_authed/dashboard/progress': typeof AuthedDashboardProgressRoute
  '/_authed/dashboard/settings': typeof AuthedDashboardSettingsRoute
  '/_authed-admin/admin/': typeof AuthedAdminAdminIndexRoute
  '/_authed/dashboard/': typeof AuthedDashboardIndexRoute
  '/_authed-admin/admin/students/$studentId': typeof AuthedAdminAdminStudentsStudentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin-access'
    | '/career-services'
    | '/certifications'
    | '/contact'
    | '/courses'
    | '/forgot-password'
    | '/reset-password'
    | '/resources'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/admin/analytics'
    | '/admin/certificates'
    | '/admin/courses'
    | '/admin/ebooks'
    | '/admin/enrollments'
    | '/admin/payments'
    | '/admin/resume-templates'
    | '/admin/settings'
    | '/admin/users'
    | '/dashboard/career-toolkit'
    | '/dashboard/certificates'
    | '/dashboard/courses'
    | '/dashboard/ebook'
    | '/dashboard/profile'
    | '/dashboard/progress'
    | '/dashboard/settings'
    | '/admin/'
    | '/dashboard/'
    | '/admin/students/$studentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin-access'
    | '/career-services'
    | '/certifications'
    | '/contact'
    | '/courses'
    | '/forgot-password'
    | '/reset-password'
    | '/resources'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/admin/analytics'
    | '/admin/certificates'
    | '/admin/courses'
    | '/admin/ebooks'
    | '/admin/enrollments'
    | '/admin/payments'
    | '/admin/resume-templates'
    | '/admin/settings'
    | '/admin/users'
    | '/dashboard/career-toolkit'
    | '/dashboard/certificates'
    | '/dashboard/courses'
    | '/dashboard/ebook'
    | '/dashboard/profile'
    | '/dashboard/progress'
    | '/dashboard/settings'
    | '/admin'
    | '/dashboard'
    | '/admin/students/$studentId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_authed-admin'
    | '/about'
    | '/admin-access'
    | '/career-services'
    | '/certifications'
    | '/contact'
    | '/courses'
    | '/forgot-password'
    | '/reset-password'
    | '/resources'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/_authed-admin/admin/analytics'
    | '/_authed-admin/admin/certificates'
    | '/_authed-admin/admin/courses'
    | '/_authed-admin/admin/ebooks'
    | '/_authed-admin/admin/enrollments'
    | '/_authed-admin/admin/payments'
    | '/_authed-admin/admin/resume-templates'
    | '/_authed-admin/admin/settings'
    | '/_authed-admin/admin/users'
    | '/_authed/dashboard/career-toolkit'
    | '/_authed/dashboard/certificates'
    | '/_authed/dashboard/courses'
    | '/_authed/dashboard/ebook'
    | '/_authed/dashboard/profile'
    | '/_authed/dashboard/progress'
    | '/_authed/dashboard/settings'
    | '/_authed-admin/admin/'
    | '/_authed/dashboard/'
    | '/_authed-admin/admin/students/$studentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AuthedAdminRoute: typeof AuthedAdminRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminAccessRoute: typeof AdminAccessRoute
  CareerServicesRoute: typeof CareerServicesRoute
  CertificationsRoute: typeof CertificationsRoute
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResourcesRoute: typeof ResourcesRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed-admin': {
      id: '/_authed-admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-access': {
      id: '/admin-access'
      path: '/admin-access'
      fullPath: '/admin-access'
      preLoaderRoute: typeof AdminAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-services': {
      id: '/career-services'
      path: '/career-services'
      fullPath: '/career-services'
      preLoaderRoute: typeof CareerServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certifications': {
      id: '/certifications'
      path: '/certifications'
      fullPath: '/certifications'
      preLoaderRoute: typeof CertificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed-admin/admin/': {
      id: '/_authed-admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthedAdminAdminIndexRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed-admin/admin/analytics': {
      id: '/_authed-admin/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthedAdminAdminAnalyticsRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed-admin/admin/certificates': {
      id: '/_authed-admin/admin/certificates'
      path: '/admin/certificates'
      fullPath: '/admin/certificates'
      preLoaderRoute: typeof AuthedAdminAdminCertificatesRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed-admin/admin/courses': {
      id: '/_authed-admin/admin/courses'
      path: '/admin/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AuthedAdminAdminCoursesRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed-admin/admin/ebooks': {
      id: '/_authed-admin/admin/ebooks'
      path: '/admin/ebooks'
      fullPath: '/admin/ebooks'
      preLoaderRoute: typeof AuthedAdminAdminEbooksRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed-admin/admin/enrollments': {
      id: '/_authed-admin/admin/enrollments'
      path: '/admin/enrollments'
      fullPath: '/admin/enrollments'
      preLoaderRoute: typeof AuthedAdminAdminEnrollmentsRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed-admin/admin/payments': {
      id: '/_authed-admin/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthedAdminAdminPaymentsRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed-admin/admin/resume-templates': {
      id: '/_authed-admin/admin/resume-templates'
      path: '/admin/resume-templates'
      fullPath: '/admin/resume-templates'
      preLoaderRoute: typeof AuthedAdminAdminResumeTemplatesRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed-admin/admin/settings': {
      id: '/_authed-admin/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthedAdminAdminSettingsRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed-admin/admin/users': {
      id: '/_authed-admin/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthedAdminAdminUsersRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/dashboard/': {
      id: '/_authed/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthedDashboardIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/career-toolkit': {
      id: '/_authed/dashboard/career-toolkit'
      path: '/dashboard/career-toolkit'
      fullPath: '/dashboard/career-toolkit'
      preLoaderRoute: typeof AuthedDashboardCareerToolkitRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/certificates': {
      id: '/_authed/dashboard/certificates'
      path: '/dashboard/certificates'
      fullPath: '/dashboard/certificates'
      preLoaderRoute: typeof AuthedDashboardCertificatesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/courses': {
      id: '/_authed/dashboard/courses'
      path: '/dashboard/courses'
      fullPath: '/dashboard/courses'
      preLoaderRoute: typeof AuthedDashboardCoursesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/ebook': {
      id: '/_authed/dashboard/ebook'
      path: '/dashboard/ebook'
      fullPath: '/dashboard/ebook'
      preLoaderRoute: typeof AuthedDashboardEbookRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/profile': {
      id: '/_authed/dashboard/profile'
      path: '/dashboard/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AuthedDashboardProfileRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/progress': {
      id: '/_authed/dashboard/progress'
      path: '/dashboard/progress'
      fullPath: '/dashboard/progress'
      preLoaderRoute: typeof AuthedDashboardProgressRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/settings': {
      id: '/_authed/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthedDashboardSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed-admin/admin/students/$studentId': {
      id: '/_authed-admin/admin/students/$studentId'
      path: '/admin/students/$studentId'
      fullPath: '/admin/students/$studentId'
      preLoaderRoute: typeof AuthedAdminAdminStudentsStudentIdRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedDashboardCareerToolkitRoute: typeof AuthedDashboardCareerToolkitRoute
  AuthedDashboardCertificatesRoute: typeof AuthedDashboardCertificatesRoute
  AuthedDashboardCoursesRoute: typeof AuthedDashboardCoursesRoute
  AuthedDashboardEbookRoute: typeof AuthedDashboardEbookRoute
  AuthedDashboardProfileRoute: typeof AuthedDashboardProfileRoute
  AuthedDashboardProgressRoute: typeof AuthedDashboardProgressRoute
  AuthedDashboardSettingsRoute: typeof AuthedDashboardSettingsRoute
  AuthedDashboardIndexRoute: typeof AuthedDashboardIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardCareerToolkitRoute: AuthedDashboardCareerToolkitRoute,
  AuthedDashboardCertificatesRoute: AuthedDashboardCertificatesRoute,
  AuthedDashboardCoursesRoute: AuthedDashboardCoursesRoute,
  AuthedDashboardEbookRoute: AuthedDashboardEbookRoute,
  AuthedDashboardProfileRoute: AuthedDashboardProfileRoute,
  AuthedDashboardProgressRoute: AuthedDashboardProgressRoute,
  AuthedDashboardSettingsRoute: AuthedDashboardSettingsRoute,
  AuthedDashboardIndexRoute: AuthedDashboardIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface AuthedAdminRouteChildren {
  AuthedAdminAdminAnalyticsRoute: typeof AuthedAdminAdminAnalyticsRoute
  AuthedAdminAdminCertificatesRoute: typeof AuthedAdminAdminCertificatesRoute
  AuthedAdminAdminCoursesRoute: typeof AuthedAdminAdminCoursesRoute
  AuthedAdminAdminEbooksRoute: typeof AuthedAdminAdminEbooksRoute
  AuthedAdminAdminEnrollmentsRoute: typeof AuthedAdminAdminEnrollmentsRoute
  AuthedAdminAdminPaymentsRoute: typeof AuthedAdminAdminPaymentsRoute
  AuthedAdminAdminResumeTemplatesRoute: typeof AuthedAdminAdminResumeTemplatesRoute
  AuthedAdminAdminSettingsRoute: typeof AuthedAdminAdminSettingsRoute
  AuthedAdminAdminUsersRoute: typeof AuthedAdminAdminUsersRoute
  AuthedAdminAdminIndexRoute: typeof AuthedAdminAdminIndexRoute
  AuthedAdminAdminStudentsStudentIdRoute: typeof AuthedAdminAdminStudentsStudentIdRoute
}

const AuthedAdminRouteChildren: AuthedAdminRouteChildren = {
  AuthedAdminAdminAnalyticsRoute: AuthedAdminAdminAnalyticsRoute,
  AuthedAdminAdminCertificatesRoute: AuthedAdminAdminCertificatesRoute,
  AuthedAdminAdminCoursesRoute: AuthedAdminAdminCoursesRoute,
  AuthedAdminAdminEbooksRoute: AuthedAdminAdminEbooksRoute,
  AuthedAdminAdminEnrollmentsRoute: AuthedAdminAdminEnrollmentsRoute,
  AuthedAdminAdminPaymentsRoute: AuthedAdminAdminPaymentsRoute,
  AuthedAdminAdminResumeTemplatesRoute: AuthedAdminAdminResumeTemplatesRoute,
  AuthedAdminAdminSettingsRoute: AuthedAdminAdminSettingsRoute,
  AuthedAdminAdminUsersRoute: AuthedAdminAdminUsersRoute,
  AuthedAdminAdminIndexRoute: AuthedAdminAdminIndexRoute,
  AuthedAdminAdminStudentsStudentIdRoute:
    AuthedAdminAdminStudentsStudentIdRoute,
}

const AuthedAdminRouteWithChildren = AuthedAdminRoute._addFileChildren(
  AuthedAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AuthedAdminRoute: AuthedAdminRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminAccessRoute: AdminAccessRoute,
  CareerServicesRoute: CareerServicesRoute,
  CertificationsRoute: CertificationsRoute,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResourcesRoute: ResourcesRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
